using System;

namespace Unity.Muse.Common
{
    static class TextContent
    {
        public static string DefaultAssetName(string modeTitle = "Muse") => $"New {modeTitle}";

        public static readonly string yes = "Yes";
        public static readonly string no = "No";
        public static readonly string cancel = "Cancel";
        public static readonly string savePopupTitle = "Unsaved changes";
        public static readonly string savePopupMessage = "There are some unsaved changes, would you like to save them?";
        public static readonly string deleteDialogTitle = "Delete Generations";
        public static readonly string deleteDialogMessage = "You are about to delete generated assets, would you like to continue?";
        public static readonly string deleteDialogOk = "Delete Selected";
        public static readonly string deleteDialogOkDontShowAgain = "Don't ask again";
        public static readonly string exportSingle = "Export";
        public static readonly string exportMultiple = "Export Selected";
        public static readonly string deleteSingle = "Delete";
        public static readonly string deleteMultiple = "Delete Selected";
        public static readonly string starSingle = "Star";
        public static readonly string unStarSingle = "Remove Star";
        public static readonly string starMultiple = "Star Selected";
        public static readonly string unStarMultiple = "Unstar Selected";
        public static readonly string refineSingle = "Refine";
        public static readonly string thumbnailSizeSliderTooltip = "Adjust thumbnails size";
        public static readonly string assetRemovedFromProjectTitle = "Delete selected generator?";
        public static readonly string assetRemovedFromProjectMessage = "'{0}'\n\nYou cannot undo the delete action.";
        public static readonly string bookmarkTooltip = "Shows only starred artifacts";
        public static readonly string bookmarkButtonTooltip = "Add to favourites";
        public static readonly string operatorGenerateNumberTooltip = "Sets the number of images to be generated.";
        public static readonly string operatorPromptTooltip = "Enter the text to describe the things that you want to generate...";
        public static readonly string operatorNegativePromptTooltip = "Enter the text to describe the things you want to exclude...";
        public static readonly string saveTooltip = "Saves selected generation(s) into project.";
        public static readonly string refineTooltip = "Refines image in canvas.";
        public static readonly string backButtonTooltip = "Snaps back the Generations panel, hides the canvas, and exits the Refine mode.";
        public static readonly string promptPlaceholder = "Enter what to generate...";
        public static readonly string savePanelTitle = "Save";
        public static readonly string savePanelMessage = "Save changes to an asset in the Project.";
        public static readonly string dragAndDropColorImageMessage = "To guide your generation, drag and drop or import a square image at 512x512 pixels or smaller";
        public static readonly string dragAndDropShapeImageMessage = "Import a <b>black and white <u><a href=\"https://en.wikipedia.org/wiki/Canny_edge_detector\">canny</a></u> image</b> to guide your generation";
        public static readonly string dislike = "Dislike";
        public static readonly string removeDislike = "Remove Dislike";
        public static readonly string like = "Like";
        public static readonly string removeLike = "Remove Like";
        public static readonly string controlMaskBrushSizeTooltip = "Adjusts the brush size (Up Arrow and Down Arrow)";
        public static readonly string controlMaskToolTooltip = "Paints a mask over the area that you want to refine.";
        public static readonly string subTitle = "Get started with Muse";
        public static readonly string subDescription1 = "<line-height=20px>Advance your projects faster with AI-powered creativity. And get new Muse capabilities regularly to improve all aspects of your game and app development.</line-height>";
        public static readonly string subStartTrial = "Try Muse for free";
        public static readonly string subStartUsing = "Start using Muse";
        public static readonly string subStartJoinTrial = "Join your organization’s trial";
        public static readonly string subStartJoinSubscription = "Join your organization’s subscription";
        public static readonly string subViewPlan = "Learn more";
        public static readonly string subViewOrganizations = "View organizations";
        public static readonly string subNoEntitlements = "You currently do not have an active subscription. <link><color=#CE3299FF>Start your subscription</color></link> to use Muse.";
        public static readonly string subConfirmTitle = "Start your 15-day\nMuse trial";
        public static readonly string subConfirmTitleTrial = "Join the Muse trial";
        public static readonly string subConfirmTitleSubscribed = "Start using Muse";
        public static readonly string subConfirmDescription1 = "<line-height=20px>With Unity Muse, you can explore, generate, learn, and test faster on Unity than ever before. Use natural language prompts to produce usable code, unique art assets, cool textures, and more. Plus, we’re regularly adding new features for all areas of game creation. Start today.</line-height>";
        public static readonly string subConfirmStart = "Start the trial";
        public static readonly string subConfirmJoinTrial = "Join the trial";
        public static readonly string subConfirmStartSubscribed = "Start using Muse";
        public static readonly string subConfirmTermsOfService = "<line-height=24px>I have read and agree to the <link=terms><color=#CE3299FF>Unity Terms of Service</color></link> and/or the applicable terms found on <link=legal><color=#CE3299FF>Unity's Legal Information page</color></link>.</line-height>";
        public static readonly string subConfirmPrivacy = "<line-height=24px>I have read and I acknowledge the <link=policy><color=#CE3299FF>Unity Privacy Policy</color></link> and the <link=supplemental><color=#CE3299FF>Generative AI Supplemental Privacy Notice</color></link>.</line-height>";
        public static readonly string subConfirmLearnMore = "Learn more";
        public static readonly string subConfirmClose = "Close";
        public static readonly string subConfirmSelectOrganization = "Choose which organization will use Muse";
        public static string subConfirmSelectOrganizationWarningSimple => $"All members of your organization will be signed up to the free trial.";
        public static string SubConfirmSelectOrganizationWarning(string org) => $"All members of the {org} organization will be signed up to the free trial.";
        public static readonly string subDataTitle = "Help us improve your\nMuse experience";
        public static readonly string subDataDescription2 = "<line-height=20px><size=12px>By opting in, you agree to let Muse use your input, generations, and usage data to improve Muse’s accuracy. Unity is committed to data protection and protects your privacy by securely storing shared data. However, never include confidential or identifiable content in your prompts.</size></line-height>";
        public static readonly string subDataLegalOptInMessage = "<line-height=20px><font-weight=600>Yes, I would like to help improve Muse by sharing content and usage data for training purposes.</font-weight></line-height>";
        public static readonly string subDataClose = "Close";
        public static readonly string subDataReadPolicy = "Read the generative AI privacy notice";
        public static readonly string subStartTitle = "A new chapter\nstarts today";
        public static readonly string subStartDescription = "Enjoy 15 days of boosted productivity with Unity Muse";
        public static readonly string subStartLearnMore = "Learn more about the trial";
        public static readonly string subUsageUsed = "Muse Points Used";
        public static readonly string subUsageExceeded = "While Muse is in early access, Point caps will not be applied.";
        public static readonly string museTitle = "Unity Muse";
        public static readonly string subStartedTitle = "Get ready to unlock\nproductivity, powered\nby AI";
        public static readonly string subStartedDesc1 = "Your trial has started";
        public static readonly string subStartedDesc2 = "<line-height=24px>You begin with 1,500 Muse Points, which can be used for any of Muse’s capabilities. Points are shared within your organization. Your trial will end after you have used 1,500 Muse Points or after 15 days, whichever comes first.</line-height>";
        public static readonly string subStartedDesc3 = "Point caps are not applied";
        public static readonly string signinTitle = "Log in to start using Muse";
        public static readonly string signinAccept = "Log in";
        public static readonly string goToMuseAccount = "Go to Muse account";
        public static readonly string tryMuse = "Start your Muse subscription now";
        public static readonly string requestSeatTitle = "You’re almost there";
        public static readonly string requestSeatDescription = "<line-height=20px>Your organization currently has a Muse subscription, so please ask your administrator to assign you a Muse seat.</line-height>";
        public static readonly string requestSeatAccept = "View organization";
        public static readonly string clientStatusDeprecatedMessage = "Your current Muse package is using a deprecated API version. You need to <link><color=#CE3299FF>upgrade your Muse package</color></link> to continue using Muse.";
        public static string ClientStatusWillBeDeprecatedMessage(DateTime date) => $"Your current Muse package is using an API version that will be deprecated on {date:MMMM dd yyyy}. You will need to <link><color=#CE3299FF>upgrade your Muse package</color></link> to continue using Muse.";
        public static readonly string clientStatusUpdateMessage = "There is a new Muse package version available <link><color=#CE3299FF>for upgrade</color></link>.";
        public static readonly string clientStatusNoInternet = "Please ensure you are connected to the internet to use Muse.";
        public static readonly string generateButtonCooldownTooltip = "Please wait before generating again.";
        public static readonly string generateButtonEnterPromptTooltip = "Enter a prompt to enable generation.";
        public static readonly string generateButtonPaintMaskTooltip = "Paint a mask to enable generation.";
        public static readonly string generateButtonEnterPromptAndPaintMaskTooltip = "Enter a prompt and paint a mask to enable generation.";
        public static readonly string failedToRetrieveArtifact = "Failed to retrieve artifact.";
        public static readonly string potentialInappropriateContentDetected = "Potentially inappropriate content.";
        public static readonly string import = "Import";
        public static readonly string importImages = "Import Images";
        public static readonly string strength = "Strength";
        public static readonly string copy = "Copy";
        public static readonly string paste = "Paste";
        public static readonly string shape = "Shape";
        public static readonly string color = "Color";
        public static readonly string patterns = "Patterns";
        public static readonly string inputImageCopiedToClipboard = "Input Image Copied to Clipboard";
        public static readonly string subNotEntitled = "This organization does not have a Muse subscription or trial.";
        public static readonly string projectSettingsTitle = "Muse";
        public static readonly string projectSettingsOrgDesc = "Select your organization";
        public static readonly string projectSettingsSignedOut = "Please log in to start using Muse.";
        public static readonly string generalSettingsCategory = "General";
        public static readonly string spriteSettingsCategory = "Muse Sprite";
        public static readonly string textureSettingsCategory = "Muse Texture";
        public static readonly string accountSettingsCategory = "Account";
        public static readonly string browse = "Browse";
        public static readonly string selectFolder = "Select Folder";
        public static readonly string deleteWithoutWarning = "Delete Generations Without Warning";
        public static readonly string spriteAssetGeneratedPath = "Default Path for Muse Sprite Assets";
        public static readonly string textureAssetGeneratedPath = "Default Path for Muse Texture Assets";
        public static readonly string canvasControlScheme = "Canvas Control Scheme";
    }
}
