using System.Runtime.CompilerServices;
[assembly: InternalsVisibleTo("Unity.Muse.Sprite.Editor")]
[assembly: InternalsVisibleTo("Unity.Muse.Sprite.Common.Editor")]
[assembly: InternalsVisibleTo("Unity.Muse.Texture.Editor")]
[assembly: InternalsVisibleTo("Unity.Muse.Common.Editor")]
[assembly: InternalsVisibleTo("Unity.Muse.Common.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.Muse.Sprite.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.Muse.Texture.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.Muse.Common")]